name: Trigger ArgoCD & Versioning  

on:
  push:
    branches:
      - dev
      - beta
      - prod
       
  workflow_dispatch:    
  
jobs:
  dev:
    if: ${{ github.ref == 'refs/heads/dev' }}
    uses: sirpi-io/bengaluru-data-stories/.github/workflows/version.yml@dev
    with:
      env: 'dev'
      image: 'anandk'
      from: 'local'
    secrets: inherit
  beta:
    if: ${{ github.ref == 'refs/heads/beta' }}
    uses: sirpi-io/bengaluru-data-stories/.github/workflows/version.yml@beta
    with:
      env: 'beta'
      image: 'anandk'
      from: 'dev'
    secrets: inherit
  prod:
    if: ${{ github.ref == 'refs/heads/prod' }}
    uses: sirpi-io/bengaluru-data-stories/.github/workflows/version.yml@prod
    with:
      env: 'prod'
      image: 'anandk'
      from: 'beta'
    secrets: inherit
