name: Trigger ArgoCD & Versioning  

on:
  push:
    branches:
      - dev
      - beta
      - prod
  pull_request:
    branches:
      - dev
      - beta
      - prod
    types: [ closed ]      
  workflow_dispatch:    
  
jobs:
  dev:
    if: ${{ github.ref == 'refs/heads/dev' }}
    uses: sirpi-io/bengaluru-data-stories/.github/workflows/version.yml@dev
    with:
      env: 'dev'
      image: 'bengaluru-data-stories'
      from: 'local'
    secrets: inherit
  prod:
    if: ${{ github.ref == 'refs/heads/prod' }}
    uses: sirpi-io/bengaluru-data-stories/.github/workflows/version.yml@prod
    with:
      env: 'prod'
      image: 'bengaluru-data-stories'
      from: 'local'
    secrets: inherit
    
