name: SonarQube Scan.

on:
  push:
    branches:
      - sonarqube

jobs:
  build:
    runs-on: sirpi

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SonarQube Scan
        uses: kitabisa/sonarqube-action@v1.2.0
        with:
          host: ${{ secrets.SONAR_HOST_URL }}
          login: ${{ secrets.SONAR_TOKEN }}
          run: |            
            /opt/sonar-scanner/bin/sonar-scanner -X \            
            -Dsonar.projectKey=bengaluru-data-stories \
            -Dsonar.sources=. \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} 
